#!/usr/bin/env sh

command -v gs > /dev/null || error "You need gs to run this script"

gs -q -dNOPAUSE -dBATCH -dSAFER			\
	-sDEVICE=pdfwrite			\
	-dCompatibilityLevel=1.5		\
	-dSimulateOverprint=true		\
	-dPDFSETTINGS=/ebook			\
	-dEmbedAllFonts=true			\
	-dSubsetFonts=true			\
	-dColorImageDownsampleType=/Bicubic	\
	-dColorImageResolution=150		\
	-dGrayImageDownsampleType=/Bicubic	\
	-dGrayImageResolution=150		\
	-dMonoImageDownsampleType=/Bicubic	\
	-dMonoImageResolution=150		\
	-sOutputFile="./cv-casalino.pdf"		\
	"./vcasalino.pdf"
